import sys
from src.CREDIT_UTILITY.logger import logger
from src.CREDIT_UTILITY.Exception import CustomException

logger.info("Welcome to custom log")

if __name__ == "__main__":
    try:
        a = 1 / 0  # This will raise a division by zero exception
    except Exception as e:
        logger.info("Divided by Zero")
        error = CustomException(e, sys)
        logger.info(error.error_message)  # Log the error message generated by CustomException
