artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts\data_ingestion
  source_URL: https://github.com/Neeraj2210/Data_Repo/raw/main/Phishing.zip
  local_data_file: artifacts\data_ingestion\data.zip
  unzip_dir: artifacts\data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Phishing.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Phishing.csv
  train_data_path: artifacts/data_transformation/Transformed/train.csv
  test_data_path: artifacts/data_transformation/Transformed/test.csv
  processed_data_path: artifacts/data_transformation/Processed
  Transformed_data_path: artifacts/data_transformation/Transformed
  Transformed_data_OBJ_PATH: artifacts/data_transformation/Processed/Transformed_data_OBJ.joblib
  Processed_data_OBJ_PATH: artifacts/data_transformation/Processed/Processed_data_OBJ.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/Transformed/train.csv
  test_data_path: artifacts/data_transformation/Transformed/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/Transformed/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json